CREATE SEQUENCE USERS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE SEQUENCE COURSES_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE SEQUENCE LESSONS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE SEQUENCE FLASHCARDS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE;