CREATE TABLE USERS(
    USER_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL
);

CREATE TABLE COURSES (
    COURSE_ID INT PRIMARY KEY,
    COURSE_NAME VARCHAR(50) NOT NULL,
    COURSE_PROGRESS DECIMAL(10, 2),
    LAST_ACCESSED DATE,
    USER_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE LESSONS (
    LESSON_ID INT PRIMARY KEY,
    LESSON_NAME VARCHAR2(50),
    LESSON_PROGRESS DECIMAL(10, 2),
    LAST_ACCESSED DATE,
    COURSE_ID INT,
    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(COURSE_ID)
);

CREATE TABLE FLASHCARDS (
    FLASHCARD_ID INT PRIMARY KEY,
    QUESTION VARCHAR2(200) NOT NULL,
    ANSWER VARCHAR2(200) NOT NULL,
    LASTACCESSED DATE,
    FLASHCARD_PROGRESS INT,
    LESSON_ID INT,
    FOREIGN KEY (LESSON_ID) REFERENCES LESSONS(LESSON_ID)
);