CREATE TABLE USERS(
    USERID INT PRIMARY KEY,
    FIRSTNAME VARCHAR2(50) NOT NULL,
    LASTNAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL
);

CREATE TABLE COURSES (
    COURSEID INT PRIMARY KEY,
    COURSENAME VARCHAR(50) NOT NULL,
    COURSEPROGRESS DECIMAL(10, 2),
    LASTACCESSED DATE,
    USERID INT,
    FOREIGN KEY (USERID) REFERENCES USERS(USERID)
);

CREATE TABLE LESSONS (
    LESSONID INT PRIMARY KEY,
    LESSONNAME VARCHAR2(50),
    PROGRESS DECIMAL(10, 2),
    LASTACCESSED DATE,
    COURSEID INT,
    FOREIGN KEY (COURSEID) REFERENCES COURSES(COURSEID)
);

CREATE TABLE FLASHCARDS (
    FLASHCARDID INT PRIMARY KEY,
    QUESTION VARCHAR2(200) NOT NULL,
    ANSWER VARCHAR2(200) NOT NULL,
    LASTACCESSED DATE,
    RATING INT,
    LESSONID INT,
    FOREIGN KEY (LESSONID) REFERENCES LESSONS(LESSONID)
);